### ISSUE TITLE
file "qkr_train.src.10000" is missing

### ISSUE THREAD

**Issue by jind11** [nlpxucan/ZRKGC#2]
When I ran "bash test.sh", I encountered this error:
Traceback (most recent call last):
  File "PPL.py", line 22, in <module>
    from PPL_modeling import BertForPreTrainingLossMask
  File "/home/ec2-user/ZRKGC/PPL_modeling.py", line 56, in <module>
    with open("qkr_train.src.10000", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'qkr_train.src.10000'

What is this file "qkr_train.src.10000"?

**Comment by nlpxucan** [comment]
I am preparing the final version for camera-ready, please wait several days, thanks

**Comment by nlpxucan** [comment]
> When I ran "bash test.sh", I encountered this error:
> Traceback (most recent call last):
> File "PPL.py", line 22, in
> from PPL_modeling import BertForPreTrainingLossMask
> File "/home/ec2-user/ZRKGC/PPL_modeling.py", line 56, in
> with open("qkr_train.src.10000", encoding="utf-8") as file:
> FileNotFoundError: [Errno 2] No such file or directory: 'qkr_train.src.10000'
> 
> What is this file "qkr_train.src.10000"?

I am preparing the final version for camera-ready, please wait several days, thanks

**Comment by yumoxu** [comment]
@nlpxucan Hi Can, thanks for your nice work! I am also facing the same problem and wondering if you have any update on this?
